AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Aws Homework Lambda Function

Resources:
  AwsHomeworkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pro.kulebyakin.awscloudxhomework.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: 's3://aws-cloudx-homework-bucket/aws-homework.jar'
      MemorySize: 1024
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
